# Generated by Django 3.2.25 on 2024-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='wow', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='power',
            field=models.CharField(default='magnetism', max_length=20),
        ),
    ]
