# Generated by Django 3.2.25 on 2024-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20240713_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo_url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
